### ISSUE TITLE
Python 3 Compatilbility

### ISSUE THREAD

**Issue by OmPrasad93** [mfaruqui/retrofitting#9]
Hi @mfaruqui ,

Is there any plan to make this code Python 3 Compatible?

**Comment by mfaruqui** [comment]
The repository is released under GNU GPL license so you can modify the code for yourself.

**Comment by OmPrasad93** [comment]
Hi Manaal,
I have sent you an email with some additional details regarding this issue. The reason is we are trying to use retrofitting in an internal module. Some additional details are present in the email. The email is sent from om.a.prasad.mohanty@accenture.com your email id as given in the repo. It would be really nice if you reply back on the same?
